### ISSUE TITLE
What is CTCAE?

### ISSUE THREAD

**Issue by cthoyt** [OAE-ontology/OAE#8]
This ontology contains several references to CTCAE, such as `CTCAE:E12396`, can you give some insight on what these xrefs are?

@e4ong1031 @yongqunh

**Comment by yongqunh** [comment]
CTCAE is a set of criteria for the standardized classification of adverse effects of drugs used in mostly cancer therapy. It is a product of the US National Cancer Institute.  
https://en.wikipedia.org/wiki/Common_Terminology_Criteria_for_Adverse_Events 

This paper provides good explanation:
https://pubmed.ncbi.nlm.nih.gov/29854250/
Title: Towards precision informatics of pharmacovigilance: OAE-CTCAE mapping and OAE-based representation and analysis of adverse events in patients treated with cancer drugs

**Comment by cthoyt** [comment]
Amazing, thank you! I will add an entry in the bioregistry for this

**Comment by yongqunh** [comment]
great. thanks!
